ask-sdk-core/ask_sdk_core/serialize.py
ask-sdk-core/tests/unit/test_api_client.py
ask-sdk-core/tests/unit/test_dispatch.py
ask-sdk-core/tests/unit/test_dispatch_components.py
ask-sdk-core/tests/unit/test_handler_input.py
ask-sdk-core/tests/unit/test_serialize.py
ask-sdk-core/tests/unit/test_skill.py
ask-sdk-core/tests/unit/test_skill_builder.py
ask-sdk-dynamodb-persistence-adapter/tests/unit/test_adapter.py
ask-sdk/tests/unit/test_standard.py
samples/ColorPicker/color_picker.py

This commit changes the test cases and other code base where
six.PY3 is used for version detection, to feature detection as
per the migration guidelines mentioned at https://docs.python.org/3/howto/pyporting.html#use-feature-detection-instead-of-version-detection
The changes are aligned with the changes done as per PR #1 , and has been done across the test cases and other areas where six.PY3 is used, to check the version. 
Going with the migration guidelines mentioned at the above python docs.

Use feature detection instead of version detection

---

README.ja.rst
README.rst
docs/en/index.rst
docs/en/models/ask_sdk_model.rst
docs/en/models/index.rst

Update model repo link in documentation. Fixes #8 
As requested by developers in #8 
Tested locally.

Update model repo link in documentation

---

docs/en/RESPONSE_BUILDING.rst
docs/en/SERVICE_CLIENTS.rst
docs/en/conf.py
docs/en/models/ask_sdk_model.services.rst
docs/en/models/ask_sdk_model.services.ups.rst
docs/ja/RESPONSE_BUILDING.rst
docs/ja/conf.py

This pull request adds the following:
- Interface, available methods and sample code for alexa service clients
- Sample code in response building
- Change pygments style to default
Better service clients documentation as per the request: https://forums.developer.amazon.com/questions/181746/why-amazon-python-team-not-providing-examples-like.html
Checked the local documentation build using Python 3.6, sphinx ``make html``.
- [] My change requires a change to the documentation

Add Service client sample code, response building sample code

---

docs/en/DEVELOPING_YOUR_FIRST_SKILL.rst
docs/en/GETTING_STARTED.rst
docs/en/HELLO_WORLD_CODE.rst
docs/en/conf.py
docs/requirements-docs.txt

Changes in documentation regarding sdk installation and developing first skill, added tabs and notes as required.
Used local doc creation command ``make html``
- [] My change requires a change to the documentation

Doc changes regarding installation instructions and developing first skill

---

docs/en/ATTRIBUTES.rst

Reword sentence to make easier to read.
Makes docs easier to read.

Improve Legibility

---

docs/en/models/ask_sdk_model.dialog.rst
docs/en/models/ask_sdk_model.interfaces.alexa.presentation.apl.rst
docs/en/models/ask_sdk_model.interfaces.alexa.presentation.rst
docs/en/models/ask_sdk_model.interfaces.alexa.rst
docs/en/models/ask_sdk_model.interfaces.amazonpay.model.request.rst
docs/en/models/ask_sdk_model.interfaces.amazonpay.model.rst
docs/en/models/ask_sdk_model.interfaces.amazonpay.rst
docs/en/models/ask_sdk_model.interfaces.amazonpay.v1.rst
docs/en/models/ask_sdk_model.interfaces.viewport.rst
docs/en/models/ask_sdk_model.services.directive.rst
docs/en/models/ask_sdk_model.services.game_engine.rst

This commit makes the following changes : 
- Adds the missing models to the docs.
- Refactors the model docs, to remove undocumented members from the autodoc modules.
- Sets toc tree depth to 1 for multi-hierarchical modules.
To set the format and to make the model documentation up-to-date.
Tested by running `make html` on local machine, and checking the docs to be generated as expected.

Add missing model docs

---

.github/PULL_REQUEST_TEMPLATE.md

Adapt PR-Template to match with [this](https://github.com/alexa/alexa-skills-kit-sdk-for-java/blob/2.0.x/.github/PULL_REQUEST_TEMPLATE.md) and [this](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/2.0.x/.github/PULL_REQUEST_TEMPLATE.md) template.

Adapt PR-Template to match other SDKs

---

ask-sdk-core/ask_sdk_core/utils/__init__.py
ask-sdk-core/ask_sdk_core/utils/request_util.py
ask-sdk-core/ask_sdk_core/utils/viewport.py
ask-sdk-core/tests/unit/test_utils.py
docs/en/api/core.rst

This commit introduces some commonly used request utility methods
like `get_locale`, `get_intent_name` etc.
Many skill developers requested to have some utility methods in the SDK, through which some commonly used boiler plate code is reduced and is provided by the SDK itself. This PR provides some of these methods.
Unit tests for the methods added. `nosetests` and `tox` run as expected. 

Add request utility methods to the SDK

---

samples/GetDeviceAddress/README.rst

I added the en sub directory into the path for the docs.  The links brought up a 404
Ran into some trouble getting Get Address to work and had incentive to read everything I could.  With broken links that was hard.
Haven't it a change in documentation

Broken Links in docs fixed

---

ask-sdk-core/ask_sdk_core/api_client.py
ask-sdk-core/ask_sdk_core/attributes_manager.py
ask-sdk-core/ask_sdk_core/serialize.py
ask-sdk-core/ask_sdk_core/skill.py
ask-sdk-core/ask_sdk_core/skill_builder.py
ask-sdk-core/setup.py
ask-sdk-core/tests/unit/test_api_client.py
ask-sdk-core/tests/unit/test_attributes_manager.py
ask-sdk-core/tests/unit/test_handler_input.py
ask-sdk-core/tests/unit/test_serialize.py
ask-sdk-core/tests/unit/test_skill.py
ask-sdk-core/tests/unit/test_skill_builder.py
ask-sdk-dynamodb-persistence-adapter/setup.py
ask-sdk-runtime/ask_sdk_runtime/dispatch.py
ask-sdk-runtime/ask_sdk_runtime/dispatch_components/exception_components.py
ask-sdk-runtime/ask_sdk_runtime/dispatch_components/request_components.py
ask-sdk-runtime/ask_sdk_runtime/skill.py
ask-sdk-runtime/ask_sdk_runtime/utils.py
ask-sdk-runtime/tests/unit/test_dispatch.py
ask-sdk/ask_sdk/standard.py
ask-sdk/tests/unit/test_standard.py

Added type comments and null check for session in RequestEnvelope and also creating py.typed files for mypy to recognize type comments
Fixed certain type comment errors raised by mypy. Also added a null check for session in AttributesManager Class since we access session.attributes from request envelope without check for session existance.
Also added py.typed files in packages so that mypy can recognize the type comments which can be used for IDE Linters, IntelliSense.
Unit tests for the methods added. `nosetests` and `tox` run as expected. 
Added py.typed files in packages IDE can functionalitites shown below
[cla]: …

Adding py.typed files to packages and type comment fixes.

---

.travis.yml
ask-sdk-core/ask_sdk_core/api_client.py
ask-sdk-core/ask_sdk_core/attributes_manager.py
ask-sdk-core/ask_sdk_core/serialize.py
ask-sdk-core/ask_sdk_core/skill.py
ask-sdk-core/ask_sdk_core/skill_builder.py
ask-sdk-core/setup.py
ask-sdk-core/tests/unit/test_api_client.py
ask-sdk-core/tests/unit/test_attributes_manager.py
ask-sdk-core/tests/unit/test_handler_input.py
ask-sdk-core/tests/unit/test_serialize.py
ask-sdk-core/tests/unit/test_skill.py
ask-sdk-core/tests/unit/test_skill_builder.py
ask-sdk-dynamodb-persistence-adapter/setup.py
ask-sdk-runtime/ask_sdk_runtime/dispatch.py
ask-sdk-runtime/ask_sdk_runtime/dispatch_components/exception_components.py
ask-sdk-runtime/ask_sdk_runtime/dispatch_components/request_components.py
ask-sdk-runtime/ask_sdk_runtime/skill.py
ask-sdk-runtime/ask_sdk_runtime/utils.py
ask-sdk-runtime/tests/unit/test_dispatch.py
ask-sdk/ask_sdk/standard.py
ask-sdk/tests/unit/test_standard.py

Creating a new PR to undo the changes done by previous PR
[Adding py.typed files to packages and type comment fixes](https://github.com/alexa/alexa-skills-kit-sdk-for-python/pull/72) which was merged without reveiwers feedback.
Unit tests for the methods added. nosetests and tox run as expected.

Reverting changes made by merged PR

---

.travis.yml
ask-sdk-core/ask_sdk_core/api_client.py
ask-sdk-core/ask_sdk_core/attributes_manager.py
ask-sdk-core/ask_sdk_core/dispatch_components/exception_components.py
ask-sdk-core/ask_sdk_core/serialize.py
ask-sdk-core/ask_sdk_core/skill.py
ask-sdk-core/ask_sdk_core/skill_builder.py
ask-sdk-core/tests/unit/test_attributes_manager.py
ask-sdk-core/tests/unit/test_skill.py
ask-sdk-core/tests/unit/test_skill_builder.py
ask-sdk-runtime/ask_sdk_runtime/dispatch.py
ask-sdk-runtime/ask_sdk_runtime/dispatch_components/exception_components.py
ask-sdk-runtime/ask_sdk_runtime/dispatch_components/request_components.py
ask-sdk-runtime/ask_sdk_runtime/skill.py
ask-sdk-runtime/ask_sdk_runtime/utils.py
ask-sdk-runtime/tests/unit/test_dispatch.py
ask-sdk/ask_sdk/standard.py

Added type comments and null check for session in RequestEnvelope and also creating py.typed files for mypy to recognize type comments
Fixed certain type comment errors raised by mypy. Also added a null check for session in AttributesManager Class since we access session.attributes from request envelope without check for session existance.
Also added py.typed files in packages so that mypy can recognize the type comments which can be used for IDE Linters, IntelliSense.
Unit tests for the methods added. `nosetests` and `tox` run as expected. 
Added py.typed files in packages IDE can functionalitites shown below
Before:
After:
IDE can recognize attributes and methods of the particular class
It is also able to validate arguments passed to the class/function.
[issues]: …

Fix for type comments and adding py.typed files for mypy linters

---

ask-sdk-core/ask_sdk_core/utils/request_util.py
ask-sdk-core/tests/unit/test_utils.py

Check the device information in request envelope, before trying to retrieve the `device_id`.
This fix is based on the [PR](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/pull/535) in ASK Node SDK.
Added test cases

Add check for device information in get_device_id utility function

---

ask-sdk-core/ask_sdk_core/attributes_manager.py
ask-sdk-core/tests/unit/data/mock_persistence_adapter.py
ask-sdk-core/tests/unit/test_attributes_manager.py
ask-sdk-dynamodb-persistence-adapter/ask_sdk_dynamodb/adapter.py
ask-sdk-dynamodb-persistence-adapter/tests/unit/test_adapter.py

The changes include adding delete attributes feature to the persistence layer.
Non-existent feature till now. Not having this feature has created issues in the past for our customers.
Unit tests for the methods added. nosetests and tox run as expected.

Add delete attributes feature to Persistence Adapter

---

ask-sdk-core/ask_sdk_core/handler_input.py
ask-sdk-core/ask_sdk_core/serialize.py
ask-sdk-core/ask_sdk_core/skill.py
ask-sdk-core/ask_sdk_core/utils/request_util.py

Fixed the mypy issue in the code comments due to which the travis build fails.
Mypy recently released a new version which caused the build fails due to following resons 
1) Fails to  recognize AnyStr from typing module. 
2) Return type of subclass function overiding superclass functions.
nosetests tests/ succeeded.

Fixing errors in travis build due to mypy

---

docs/en/SERVICE_CLIENTS.rst

Adding Code Sample Section to interact with the Alexa Customer Settings API via UpsServiceClient
Added a "Code Sample" section underneath "UpsServiceClient" showing how to use the Phython ASK SDK to access the three pieces of information provided by the Alexa Settings API specifically: time zone, preferred distance measurement and preferred temperature unit. Also provided a brief summary explaining the data types returned by the SDK in this section and how to access the desired data.
Due to this lack of code sample, it took me longer than I would like to admit to properly use the Python ASK SDK to fetch basic information provided by the Alexa Settings API. Having figured out how to access these three pieces of basic information from the Alexa Settings API, I'd like to offer my own code …

Adding Code Sample Section for UpsServiceClient

---

README.rst
docs/en/OUT_OF_SESSION_SERVICE_CLIENTS.rst
docs/en/REQUEST_PROCESSING.rst
docs/en/RESPONSE_BUILDING.rst
docs/en/SDK_SUPPORTED_ALEXA_CAPABILITIES.rst
docs/en/SERVICE_CLIENTS.rst
docs/en/index.rst
docs/en/models/ask_sdk_model.interfaces.alexa.presentation.apl.rst
docs/en/models/ask_sdk_model.services.lwa.rst
docs/en/models/ask_sdk_model.services.proactive_events.rst
docs/en/models/ask_sdk_model.services.rst
docs/en/models/ask_sdk_model.services.skill_messaging.rst

This commit adds documentation for 
- Out of session service clients
- Catching up on missing alexa capabilities that are already supported by the SDK
- Missing model definitions for recently released support
Provides more information on how to use SDK for services that run out-of-skill-session. 
Generated locally using the `make html` option.

Documentation for out-of-session service clients, missing models

---

README.rst
ask-sdk-webservice-support/ask_sdk_webservice_support/verifier.py
ask-sdk-webservice-support/ask_sdk_webservice_support/verifier_constants.py
ask-sdk-webservice-support/ask_sdk_webservice_support/webservice_handler.py
docs/en/SAMPLE_SKILLS.rst
docs/en/SERVICE_CLIENTS.rst
docs/en/api/webservice.rst

This commit makes the following changes : 
- Update docstrings in `webservice_handler`, to reflect correctly on the model definitions
- Update comment formats in `verifier_constants`, to reflect on the model definitions
- Other documentation formatting, to remove warnings during local document generation using `make html`.
-----
From local html generated through `make html`
-------

Update webservice docstrings to reflect in rtd documentation

---

ask-sdk-core/ask_sdk_core/utils/__init__.py
ask-sdk-core/ask_sdk_core/utils/request_util.py
ask-sdk-core/tests/unit/test_utils.py

Helper function to get user id from request.
The method retrieves the userId from the input request. This value uniquely identifies the user and is generally used as input for some Alexa-specific API calls.
nosetests tests succeeded.

Add helper function to fetch userId

---

ask-sdk-core/ask_sdk_core/utils/viewport.py
ask-sdk-core/tests/unit/test_utils.py

Add support for the HUB_LANDSCAPE_SMALL viewport used by the Echo Show 5.
Supporting `Echo Show 5` viewport mapping utility function in the SDK.
Added unit tests

Add support for the HUB_LANDSCAPE_SMALL (Echo Show 5) viewport

---

ask-sdk-runtime/ask_sdk_runtime/dispatch.py
ask-sdk-runtime/ask_sdk_runtime/dispatch_components/request_components.py
ask-sdk-runtime/tests/unit/test_dispatch.py

This fixes the regression caused due to updating the `dispatch` method call on the response interceptors processing, introduced during this [commit](https://github.com/alexa/alexa-skills-kit-sdk-for-python/commit/f9acb901334b0b50e3e9e67b0be52aa304be196c#diff-fa8e4d9ff4e1eae76b211b3b0bd11efaL122). This fixes #91 
tox tests passed. Also tried with a sample code for response interceptor as provided in #91 

Fix response interceptor keyword argument

---

.travis.yml
tox.ini

Updated the travis.yml file to run tox command.
Updated the travis.yml file to run tox command which is currently used to test sdk installations and run unit tests from all components locally also mypy checks can be added to the same. Making sure travis CI also runs the same, hence local and travis testing will be synchronized.
Travis CI build shows success for all three python env.

Update Travis to run tox

---

.travis.yml
tox.ini

This commit introduces os specific builds to tox, particularly for `linux`, `mac` and `windows` on `py27`, `py36` and `py37` python versions.
By adding os' specific builds to tox, sdk developers can retroactively run tests and catch issues in SDK like #89 even before changes and PRs are pushed to the code.
Downside of this change is that the [travis builds](https://travis-ci.org/nikhilym/alexa-skills-kit-sdk-for-python/builds/543590195) take more time now (~around 6 minutes over-all, most of the time is because of the `beta` windows builds [downloading and installing python](https://docs.travis-ci.com/user/languages/python/#running-python-tests-on-multiple-operating-systems) before using it).
- [Travis build](https://travis-ci.org/nikhilym/alexa-skills-kit-sdk-for-python/builds/543590195) …

Add os specific builds in tox

---

README.ja.rst
README.rst
docs/en/SDK_SUPPORTED_ALEXA_CAPABILITIES.rst
docs/ja/SDK_SUPPORTED_ALEXA_CAPABILITIES.rst

Update docs and README to move Connections from Preview to Stable

Update docs and README to move Connections from Preview to Stable

---

docs/en/WEBSERVICE_SUPPORT.rst

Update WEBSERVICE_SUPPORT.rst django_ask_sdk contains skill_adapter not skill_response

---

flask-ask-sdk/README.rst

The code example for the `flask_ask_sdk` docs  is misisng the SkillAdapter import, so the code does not run.
Making docs clearer for future users.
Copied the docs code and ran it. It works now.

Add SkillAdapter import to example code

---

README.ja.rst
README.rst
ask-sdk-core/README.rst
ask-sdk-dynamodb-persistence-adapter/README.rst
ask-sdk-webservice-support/README.rst
ask-sdk/README.rst
django-ask-sdk/README.rst
flask-ask-sdk/README.rst
samples/GetDeviceAddress/README.rst

Update links in the README files to point to the docs on developer.amazon.com
The documentation is now hosted on developer.amazon.com, so this updates the links to point to the docs at the new location
Checked all the link targets
n/a

Update README links to developer.amazon.com

---

README.ja.rst
README.rst
ask-sdk-webservice-support/README.rst
ask-sdk-webservice-support/setup.py
django-ask-sdk/README.rst
django-ask-sdk/setup.py
flask-ask-sdk/README.rst
flask-ask-sdk/setup.py

This PR changes the documentation for the GA release of webservice adapters. The PR also adds type-hinting support for webservice adapters.
Moving webservice adapters from Beta to GA
`tox` success

Change webservice adapters documentation for GA release

---

ask-sdk-s3-persistence-adapter/tests/unit/test_adapter.py

- Fixes the unit tests for s3 package, to run windows build.
- Travis [build](https://travis-ci.org/alexa/alexa-skills-kit-sdk-for-python/jobs/583308954) failures
Local and [travis](https://travis-ci.org/nikhilym/alexa-skills-kit-sdk-for-python/builds/588266135) builds succesful.

Fix unit tests to use os.sep for windows build

---

.gitignore
.travis.yml
ask-sdk-core/ask_sdk_core/serialize.py
tox.ini

Mypy new verison was released which required bytes type comment to be explicitly mentioned for mypy checks to pass.
Also, disabled pip upgrade and forcing python version 3.7.4 since there seems to be an issue with in [Travis Windows CI](https://travis-ci.community/t/windows-python-pip-module-not-found/5480).
Travis build succedded in all platforms.

Travis build failures fix

---

ask-sdk-webservice-support/ask_sdk_webservice_support/verifier.py

`urlopen` in `Python2.7` doesn't have context management support. This leads to exception when trying to load the request certificate as mentioned in #122 . This PR fixes the issue by explicitly adding `closing` on top of urlopen, as suggested in the official docs [here](https://docs.python.org/2/library/contextlib.html#contextlib.closing).
Fixes #122 
Tested with a sample flask skill on Python 2.7 and Python 3.7, with and without request verification, to check that the changes do not cause any regression and works as expected.

Add context manager on urlopen in request verifier

---

ask-sdk-dynamodb-persistence-adapter/ask_sdk_dynamodb/partition_keygen.py
ask-sdk-dynamodb-persistence-adapter/tests/unit/test_partition_keygen.py

Provide a partition key generator for person id, when person id exists on the request envelope. This is similar to the PR on Java SDK [here](https://github.com/alexa/alexa-skills-kit-sdk-for-java/pull/229)
Java SDK PR.
- Added unit tests.

Add personId partitionKey generator

---

ask-smapi-sdk/.gitignore
ask-smapi-sdk/CHANGELOG.rst
ask-smapi-sdk/LICENSE
ask-smapi-sdk/MANIFEST.in
ask-smapi-sdk/NOTICE.txt
ask-smapi-sdk/README.rst
ask-smapi-sdk/THIRD-PARTY.txt
ask-smapi-sdk/ask_smapi_sdk/__init__.py
ask-smapi-sdk/ask_smapi_sdk/__version__.py
ask-smapi-sdk/ask_smapi_sdk/smapi_builder.py
ask-smapi-sdk/ask_smapi_sdk/utils.py
ask-smapi-sdk/requirements.txt
ask-smapi-sdk/setup.cfg
ask-smapi-sdk/setup.py
ask-smapi-sdk/tests/unit/test_builder.py
ask-smapi-sdk/tests/unit/test_util.py

Created ASK SMAPI SDK Package.
ASK SMAPI SDK is the Python library package for Alexa Skill Management API (SMAPI). SMAPI is a set of API operations that allow you to programmatically manage and test Alexa skills and related resources such as interaction models. More information on SMAPI can be found at [Alexa Developer Documentation](https://developer.amazon.com/docs/smapi/smapi-overview.html).
nosetests tests/  under the ask-smapi-sdk succeded.

Adding ASK SMAPI SDK Package

---

ask-smapi-sdk/README.rst

`ServiceExceptions` have a `body` attribute which contains vital debug info, but no `message` attribute.
Builtin errors (_i.e.,_ `TypeErrors`) have neither attribute; debug info is available via a simple `print` of the error object itself.
Opted for a Pythonic one-liner. e.g., "print the attribute if it exists, else print the object"
Examples in README cause errors while… trying to print errors.
Walked through an example in pdb.

Fix error message print in README example

---

.travis.yml
README.rst
ask-smapi-sdk/README.rst
scripts/ci/run_tests
scripts/ci/sdk_install
tox.ini

Updating README with smapi-sdk downloads and version from PyPI and adding the smapi-sdk package to run_tests on different python versions and added mypy checks in tox.
- Travis CI successfully built on all platforms. 
- Windows is throwing an [error](https://travis-ci.org/Shreyas-vgr/alexa-skills-kit-sdk-for-python/jobs/623879396?utm_medium=notification&utm_source=github_status) on installing python3 from chocolatey which is not related to this PR.

Update README and tox tests

---

ask-sdk-core/ask_sdk_core/api_client.py

Changing the literal check as it throws a syntax error in Python 3.8. Surprisingly, this works fine in both Python 2.7 (which is EOL at last. Hurray 😄 !!) and Python 3.6/3.7. Also this has been already addressed in `ask-sdk-model-runtime` package.
#127 
tox tests

Change incorrect literal check

---

README.ja.rst
README.rst
docs/ja/SDK_SUPPORTED_ALEXA_CAPABILITIES.rst

update link for requesting customer contact info.

Update link for requesting customer contact info

---

ask-sdk-core/ask_sdk_core/utils/request_util.py

Updating slot helper to get through type hinting of slot helpers
tox success
- [] My change requires a change to the documentation

Update slot helpers to fix mypy issues

---

.travis.yml
ask-sdk-local-debug/.coveragerc
ask-sdk-runtime/tests/__init__.py
ask-sdk/tests/__init__.py
ask-smapi-sdk/tests/__init__.py
django-ask-sdk/tests/__init__.py
flask-ask-sdk/.coveragerc
mypy.ini
scripts/ci/run_tests
scripts/ci/sdk_install
tox.ini

Travis Build Fix and Added Python 3.8 env
Fixed current build failures and added python 3.8 travis build check for linux, win and macOS platforms.
Had to run nosetests outside tests/ for windows python 3.8 build to success, Also mypy didn't pick up mypy.ini config so had to add `--ignore-missing-imports --no-strict-optional` for ask-sdk-local-debug tests.
Travis Build Success.

Travis Build Fix and Added Python 3.8 env

---

ask-sdk-core/ask_sdk_core/skill.py
ask-sdk-core/ask_sdk_core/skill_builder.py
ask-sdk-core/tests/unit/test_skill_builder.py
ask-sdk-runtime/ask_sdk_runtime/utils.py
ask-sdk-runtime/tests/unit/test_utils.py

This commit introduces the following changes :
- A static user agent manager, that will handle component registration
and retrieve user agent
- skill builder changes, to use UserAgentManager static class, for appending
SDK user agent.
To allow frameworks built on the SDK, to provide user agent information without registering themselves to the skill builder. This way, frameworks can register user agents and create a skill context outside of skill builder, and still get the required user agent from the SDK.
Unit tests added.

Add UserAgentManager, for adding custom user agents outside skill context

---

ask-sdk-webservice-support/ask_sdk_webservice_support/__version__.py
ask-sdk-webservice-support/requirements.txt

Update the cryptography min version to 3.2, as per this security vulnerability report : https://github.com/alexa/alexa-skills-kit-sdk-for-python/network/alert/ask-sdk-webservice-support/requirements.txt/cryptography/closed
https://github.com/alexa/alexa-skills-kit-sdk-for-python/network/alert/ask-sdk-webservice-support/requirements.txt/cryptography/closed
- Unit tests passes fine.
- Created new flask skill , used dependencies from latest change and could get the skill working as expected locally.
- [] My change requires a change to the documentation
- [] I have added tests to cover my changes

Change min version of cryptography for security vulnerability fix

---

ask-sdk-local-debug/ask_sdk_local_debug/config/skill_invoker_config.py
scripts/ci/sdk_install
tox.ini

This commit adds the skill handler directory into the PYTHONPATH variable, so that while running the skill handler file, local python modules/packages imports works as expected. This is to stimulate the behavior of running the skill lambda handler as the main file from the python interpreter.
The PR also includes fixes in `tox` files, so that GH actions passes for windows subsystems. They were working as expected before, but looks like the newer machines need the explicit python interpreter passed to `pip install` commands.
Fixes #183 
Tested the local debugger to be working as expected, for the skill sample : https://github.com/alexa/skill-sample-python-city-guide/tree/master/lambda/py, without making the change in the skill handler file as suggested here : …

fix: Add skill handler directory in pythonpath, for local imports. Fixes #183

---

.gitignore
ask-sdk-local-debug/ask_sdk_local_debug/client/autobahn_client.py
ask-sdk-local-debug/ask_sdk_local_debug/client/autobahn_client_protocol.py
ask-sdk-local-debug/tests/unit/test_autobahn_client_protocol.py
ask-sdk-webservice-support/tests/unit/test_verifier.py
ask-smapi-sdk/README.rst
tox.ini

This PR addresses Github Actions failures fix
- fixed issue on ask-sdk-webservice-support/tests/unit/test_verifier.py.
- configured tox to install latest mypy 
- remove duplicate redundant code in ask-sdk-local-debug test files
- Updated `ask-smapi-sdk` readme instructions on retrieving LWA refresh token using ASK-CLI.
- All workflows successful on Github Actions.

Github Action failure fixes

---

ask-sdk-core/tests/unit/test_response_helper.py

- fix: directive test case bug fix
- nosetests test success

fix: directive test case bug fix

---

docs/en/models/ask_sdk_model.services.reminder_management.rst

docs: update docs on reminder_management

docs: update docs on reminder_management

---

ask-sdk-core/ask_sdk_core/view_resolvers/locale_template_enumerator.py

- fix: added "#type:ignore" on files causing issues due to lastest mypy version update
- tested mypy locally and success without any errors.
- Github Actions passes.

fix: added "#type:ignore" on files causing issues due to lastest mypy version update

---

ask-sdk-core/ask_sdk_core/response_helper.py
ask-sdk-core/tests/unit/test_response_helper.py

- feat: adding A/B testing SPIs to core package
- Duplicate of PR #195 , fixed the Github Actions failures in this PR.
- All unit tests cases passes
- Github Actions success

feat: adding A/B testing SPIs to core package

---

CHANGELOG.rst
ask-sdk-core/CHANGELOG.rst
ask-sdk-core/ask_sdk_core/__version__.py
ask-sdk-dynamodb-persistence-adapter/CHANGELOG.rst
ask-sdk-dynamodb-persistence-adapter/ask_sdk_dynamodb/__version__.py
ask-sdk-runtime/CHANGELOG.rst
ask-sdk-runtime/ask_sdk_runtime/__version__.py
ask-sdk/CHANGELOG.rst
ask-sdk/ask_sdk/__version__.py

Release 1.17.1. For changelog, check CHANGELOG.rst
Github Actions successs

Release 1.17.1. For changelog, check CHANGELOG.rst
