ask-sdk-core/ask_sdk_core/api_client.py
ask-sdk-core/tests/unit/test_api_client.py

This commit changes the data from request body to raw data using
json dumps method, so that the ``requests`` library uses the
stringified raw data for requests.
Fixes #11 
Added sample test case that stringifies the request data before calling the API. Tested a sample progressive response skill using the following code sample on Python 2.7 with ask-sdk installed: 
```
from ask_sdk_core.handler_input import HandlerInput
from ask_sdk_model.services.directive import (
SendDirectiveRequest, Header, SpeakDirective)
def call_directive_service(handler_input):
request_id_holder = handler_input.request_envelope.request.request_id
directive_header = Header(request_id=request_id_holder)
speech = SpeakDirective(speech="Ok, give me a minute")
s = SendDirectiveRequest(header=directive_header, …
```

[Fix]: Send stringified raw data to Alexa APIs

---

ask-sdk-core/ask_sdk_core/skill_builder.py
ask-sdk-core/tests/unit/test_skill_builder.py

This commit removes the strict check of having corresponding
arguments passed in the decorated functions (request_handler,
exception_handler, global_request_interceptor,
global_response_interceptor), which was surfaced as part of
using type annotations in Python 3.x (Issue #20).
The ``inspect.getargspec`` function usage is being deprecated in
Python 3 and without these checks, the default error message thrown
to the user is good enough to debug.
Fixes #20.
Issue #20
Ran unit tests through ``scripts/ci/run_tests`` on the SDK installed using ``scripts/ci/sdk_install``

Remove inspect.getargspec from sb decorators

---

ask-sdk-dynamodb-persistence-adapter/ask_sdk_dynamodb/adapter.py
ask-sdk-dynamodb-persistence-adapter/tests/unit/test_adapter.py

Enable consistent reads for the get_attributes method from DynamoDB Adapter. This makes the reads consistent if the user is reading the attributes immediately after a ``save``.

Enable consistent reads through DynamoDb adapter

---

ask-sdk-core/ask_sdk_core/api_client.py
ask-sdk-core/requirements.txt

This PR includes changes to the default API client class, so that the raw data is sent to the Alexa service clients only if the ``request.body`` is not null. Without that, ``requests`` library calls leads to incorrect content type for responses, as mentioned in #38 .
The PR also includes scoping requests library to <= 2.19.1, which scopes urllib3 < 1.24, without which the ``standard`` and ``dynamo`` package installations might fail. This can be checked from the build failure of docs [here](https://readthedocs.org/projects/alexa-skills-kit-python-sdk/builds/7970861/)
#38 
Ran sdk tests using ``scripts/ci/run_tests``
[cla]: …

Send data to ServiceClients only if present

---

ask-sdk-core/ask_sdk_core/utils/__init__.py
ask-sdk-core/ask_sdk_core/utils/predicate.py
ask-sdk-core/tests/unit/test_utils.py

Provide matching helper function for `IntentRequest`-specific `is_intent_name()` to `CanFulfillIntentRequest`... for use in `can_handle()`.
Follow DRY principles.
Simply intent matching. 
i.e., 
```
return (
is_request_type('CanFulfillIntentRequest')(handler_input) and
handler_input.request_envelope.request.intent.name == 'MyIntent'
)
```
to...
```
return is_canfulfill_intent_name('MyIntent')(handler_input)
```

Add helper function for matching CanFulfill Intent name

---

ask-sdk-core/ask_sdk_core/serialize.py

This PR involves adding a check on the `deserialize` method, to only deserialize if the payload is not None. This check was present on the `DefaultSerializer.deserialize` method, which will only check the top level but do not check the values recursively. This fix will check the recursive values inside the JSON before deserializing.
This change was because of issue #47 . Effectively, [Alexa GetList](https://developer.amazon.com/docs/custom-skills/access-the-alexa-shopping-and-to-do-lists.html#getList) API provides a list with attribute `links` as null, but the SDK expects it to be a list of values.  
Tried the following code snippet to be working as expected, after the fix : 
`class LaunchRequestHandler(AbstractRequestHandler):
"""Handler for skill launch."""
def can_handle(self, …

Deserialize only if payload is not None

---

ask-sdk-core/ask_sdk_core/__version__.py
ask-sdk-core/setup.py
ask-sdk-dynamodb-persistence-adapter/ask_sdk_dynamodb/__version__.py
ask-sdk-dynamodb-persistence-adapter/setup.py
ask-sdk-runtime/ask_sdk_runtime/__version__.py
ask-sdk-runtime/requirements.txt
ask-sdk-runtime/setup.py
ask-sdk/ask_sdk/__version__.py
ask-sdk/setup.py

This commit makes the following changes:
- Set 'typing' package to be installed only on Python 2.7. This fixes the import issue raised in Python 3.7, on using the 'typing 3.6' module, as mentioned in issue #49.
- Remove dependencies on enum34 and typing from extra_requires fields in setup files, since these are installed as dependencies in ask-sdk-model package.
- Set the install_requires dependencies to follow the same version as mentioned in requirements.txt in all ask-sdk* packages.
Fixes #49 , making the SDK compatible with Python 3.7
Ran tox and tested with couple of sample skills on Python 3.6, Python 3.7
[cla]: …

Refactor dependencies for python versions

---

ask-sdk-core/ask_sdk_core/serialize.py
ask-sdk-core/tests/unit/data/model_test_object_3.py
ask-sdk-core/tests/unit/data/model_test_object_4.py
ask-sdk-core/tests/unit/test_serialize.py

Instead of having duplicated keys between `attribute_map` and `deserialized_types`, this PR allows to completely leave out `attribute_map` in serialized classes, if you don't want to do any renaming between the native and serialized representations.
An example:
```python
class User:
deserialized_types = {
'name': 'str',
'age': 'int'
}
def __init__(self, name='', age=0):
self.name = name
self.age = age
u = User('joe', 42)
serializer = DefaultSerializer()
serializer.serialize(u) # {'name': 'joe', 'age': 42}
```
This PR is a follow-up on the discussion in #58. I'm using the serializer in my projects too, as I found it super useful. However I found the repetition of attribute names unnecessary and decreasing the readability of my models.
I ran the tests locally (OS X, py3.6), all passed. Note …

Makes attribute_map optional for serializing

---

ask-sdk-core/ask_sdk_core/response_helper.py
ask-sdk-core/tests/unit/test_response_helper.py

Add PlayBehavior optional parameter on response builder speak, ask methods
This commit includes the optional parameter play_behavior on ResponseFactory's
speak and ask methods, to include the Speech Interruption property
PlayBehavior as mentioned in the [Alexa Response structure definition](https://developer.amazon.com/docs/custom-skills/request-and-response-json-reference.html#outputspeech-object).
`PlayBehavior` attribute on Alexa `Response` provides a way to interrupt Alexa speech, which is useful during some skill development like game skills. Since Response Builder is the SDK's way of generating the response, we need to provide a way to add this attribute on the `speak` and `ask` commands of the builder, for skill developers to use.
Added tests, tox works fine.
[issues]: …

Add PlayBehavior optional parameter on response builder speak, ask methods

---

ask-sdk-core/ask_sdk_core/api_client.py
ask-sdk-core/tests/unit/test_api_client.py

This commit makes a change in the default api client - request body
serialization. The earlier code has a conversion for the request
body to convert to json before triggering the APIs, without checking
the content type of the request. This would make incorrect API calls
if the request body is not of type JSON. This commit checks if the
request body content is of type json and only convert it. If not,
then send in the body unconverted, leaving the initial input as is.
To allow default api client, to call Alexa-APIs that has other than `application/json` body content
Corresponding tests has been added to the default api client test suite. tox tests are successful.
[cla]: …

Change default api client request body serialization

---

docs/en/_static/css/custom.css
docs/en/conf.py

Custom css being added to the documentation configuration, so that the text wraps in headers and code descriptions
Issue #70 
Tested locally by running `make html`. 

Add custom css to wrap the overflow values in documentation

---

ask-sdk-webservice-support/ask_sdk_webservice_support/__version__.py
ask-sdk-webservice-support/ask_sdk_webservice_support/webservice_handler.py
ask-sdk-webservice-support/tests/unit/test_webservice_handler.py
django-ask-sdk/django_ask_sdk/__version__.py
django-ask-sdk/django_ask_sdk/skill_adapter.py
django-ask-sdk/tests/unit/test_skill_adapter.py
flask-ask-sdk/flask_ask_sdk/__version__.py
flask-ask-sdk/flask_ask_sdk/skill_adapter.py
flask-ask-sdk/tests/unit/test_skill_adapter.py
scripts/ci/run_tests
scripts/ci/sdk_install
tox.ini

This commit contains the following changes :
- The custom user agent in webservice support and corresponding packages were being set on skill during initialization. The user agent value is not set until the skill is invoked, leading to a ValueError. This commit fixes this issues. Fixes #82
- Added webservice support and corresponding packages to install and run tests scripts, so that tox will run all package tests.
- Set the `url` values under the webservice and corresponding packages to the correct github repo, to reflect on PyPI
Fixes #82 
Tox runs fine. Also tested using the sample code posted by the customer in issue #82 
[cla]: …

Set custom user agent correctly, run webservice tests on tox

---

ask-sdk-webservice-support/ask_sdk_webservice_support/verifier_constants.py

This commit makes the verfier_constants path from posix path to os
specific path check, which helps in valid request verification in
other than posix os. This also fixes the docstring links to refer the correct sections. Additionally, it also sets the default tolerance value for timestamp verifier to 150 seconds as mentioned in the documentation.
This is the requested fix for PR #89 . Raising one for community review since the other PR is not yet changed.

Update os specific verifier constant path

---

ask-sdk-core/ask_sdk_core/skill_builder.py

Update the type hint for skill_builder's [``lambda_handler``](https://github.com/alexa/alexa-skills-kit-sdk-for-python/blob/master/ask-sdk-core/ask_sdk_core/skill_builder.py#L80) , to reflect the (de) serialization component. Also add docstring information to mention how the ``lambda_handler`` is processing the input from AWS Lambda.
Fixes #93 . Since `sb.lambda_handler` is specific to AWS Lambda, the underlying function should only accept parameter types specific to Lambda processing. So changing the type hinting to reflect that. Also mentioning more information on how this is processed in the skill code.
Generated sphinx docs locally to check the docstrings. Checked the automated documentation in IDE's to reflect the type hints. Since the `lambda_handler` function is a wrapper function …

Update docstring and type hint for lambda_handler

---

ask-sdk-core/ask_sdk_core/attributes_manager.py
ask-sdk-core/tests/unit/test_attributes_manager.py
docs/en/ATTRIBUTES.rst
docs/ja/ATTRIBUTES.rst

This commit fixes the delete persistence attributes method call in attributes manager
to call the delete item method even if the persistence attributes set boolean is not
available. Since delete item is idempotent and there might be cases where skill devs
might have to delete the attributes even before retrieving them, this needs to be
fixed.
The commit also adds the documentation for delete attributes call.
#97 
Tox tests run successfully. Tried with sample skill.

Delete persistence attributes without checking setter

---

ask-sdk-core/ask_sdk_core/utils/request_util.py
ask-sdk-core/tests/unit/test_utils.py

Change get_slot_value function to return None when slot is not present
Instead of throwing an error, it would be better to return null when the slot is not present in requestEnvelope. Thus developer don't need to check whether the slot is existed before calling this util function.
See above description
Changed the unit test and all unit tests passed.

Change get_slot_value function to return None when slot is not present

---

ask-sdk-core/ask_sdk_core/attributes_manager.py
ask-sdk-core/tests/unit/test_attributes_manager.py
ask-sdk-core/tests/unit/test_skill_builder.py

An `AttributesManagerException` was being raised during `AttributesManager.__init__` (called every time a skill is invoked) if the incoming request had no session object. That was removed, as AudioPlayer callbacks have no session object.
Again, at least AudioPlayer callbacks (presumably others?) have no session object.
Ironically, in order to add this change several months ago, the existing "out-of-session" AttributeManager tests (which would have caught this error) had a `session=Session()` added to the request_envelope so they would (erroneously) pass. In addition to changing those back to `session=None`, a new test was added to test that out-of-session skill invocation was possible.
[license]: …

Allow out-of-session requests

---

ask-sdk-core/README.rst

Incorrect reStructuredText was breaking most of the URLs preventing someone from clicking on the link (characters %3E%60 were added to the hyperlink).
Incorrect reStructuredText was breaking most of the URLs preventing someone from clicking on the link (characters %3E%60 were added to the hyperlink).
Anyone that wants to learn more about the SDK via the links in the Readme will need to copy the URL text instead of clicking on the link because of the incorrect reStructuredText, which was added invalid characters to the hyperlink.
Changes were made to the reStructuredText to align with guidelines; previewed changes.
n/a
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] My code follows the code style of this project
- [ x] I have updated the documentation accordingly
- [ x] I …

Fixed broken URL links

---

ask-sdk-webservice-support/ask_sdk_webservice_support/verifier.py
ask-sdk-webservice-support/tests/unit/test_verifier.py

Requests should be handled if they fall +/- within a preset tolerance. Requests with (what should have been) a negative delta within the preset tolerance were raising an exception.
`timedelta.seconds` is always a positive integer. For `x - y`, if `x` is smaller (earlier) than `y`, you get "the number of seconds in a day minus the delta" instead of "a negative delta".
```
from datetime import datetime, timedelta
first = datetime.now()
second = datetime.now()
print((first - second).seconds)  # ~ 86397
print((first - second.total_seconds())  # ~ -2.497155
```
What was intended was most likely `timedelta.total_seconds()`, which returns a true (negative-possible float) delta.
If the server's datetime is fractionally faster than the requests datetime, it'll raise a `ValidationException`. …

Fix TimestampVerifier delta check

---

ask-smapi-sdk/README.rst

Imported class name was incorrect, missing "Client" in the name.
`.client()` is easy to miss "beyond the fold" at the end of a long line of code, I moved it to the next line.
Can't import the Class with the wrong name.
Tests already existed. The example in the README was just misspelled. 

Fix class name in example in README

---

ask-sdk-webservice-support/ask_sdk_webservice_support/verifier.py

Since header keys can be case-insensitive as per the [RFC 2616 doc](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2), we need to retrieve them correctly before retrieving the certificate for request verification.
#136 
tox tests ran successfully. Travis seems to fail because of invalid Python version on Macos new xcode package. Will check as per another PR.
- [] I have added tests to cover my changes

Retrieve case-insensitive header values

---

ask-sdk-webservice-support/ask_sdk_webservice_support/verifier.py
ask-sdk-webservice-support/ask_sdk_webservice_support/verifier_constants.py
ask-sdk-webservice-support/tests/unit/test_verifier.py

Decouples the verification tolerances for standard skill requests and skill event requests which have different maximums.
Due to the delivery characteristics of skill event requests, these requests may arrive with a timestamp value of up to 1 hour prior to the current time and are verified against a different upper bound value than standard requests.
Standard requests should be verified within 150 seconds. This change splits the verification logic of the two request classes.
https://developer.amazon.com/en-US/docs/alexa/smapi/skill-events-in-alexa-skills.html#delivery-of-events-to-the-skill
Unit tests added. Existing tests pass.
[cla]: …

Change maximum timestamp verifier tolerance values as per guidelines

---

ask-sdk-core/ask_sdk_core/__version__.py
ask-sdk-core/requirements.txt

This PR fixes the minimum version of `ask-sdk-runtime` package, that is required for user agent registration changes in `ask-sdk-core` package .
Fixes #175 
- Tested with old `runtime` package, `pip install ask-sdk-core` before and after the changes, to check if the latest runtime package is picked up for installation.

Fix runtime min version for user agent registration

---

ask-sdk-core/ask_sdk_core/response_helper.py
ask-sdk-core/tests/unit/test_response_helper.py
tox.ini

- Adding Directive support for RePrompt SPI, 
- Created `add_directive_to_reprompt` method in Response helper and added new test cases 
- nosetests tests success with latest model release

feat: Adding Directive support for RePrompt SPI

---

ask-sdk-webservice-support/ask_sdk_webservice_support/verifier.py
ask-sdk-webservice-support/ask_sdk_webservice_support/verifier_constants.py
ask-sdk-webservice-support/tests/unit/test_verifier.py

Upgrading the ASK SDK Python WebService skill request signature verification handler to use the SHA256withRSA signature algorithm using the Signature-256 request header in order to validate the request is a valid Alexa HTTP requests.
This change is part of a multi-phase effort to move off of SHA-1 algorithm for all tls usage.

update signature algorithm validation from sha-1 to sha-256
